### ISSUE TITLE
Requesting help with a problem for reproducing example

### ISSUE THREAD

**Issue by iamcqlin** [mturiansky/nonrad#2]
Dear all developers or users:

Nonrad is a very powerful code. However, as I am a beginner with nonrad, I had some problems repeating the developer's tutorial.

As a rookie I have tried to repeat this literature "Nonrad: Computing nonradiative capture coefficients from first principles".

I calculated the Configuration Coordinate Diagram , the calculation results look consistent with the example.
![image](https://user-images.githubusercontent.com/37436429/161024913-112dba74-feb5-45e3-83d5-ceae611dfac4.png)

When i calculate the Electron-Phonon Coupling Matrix Element，I found that a large error is produced. The graph I calculated is shown below.
![image](https://user-images.githubusercontent.com/37436429/161025846-8c23554c-cfa2-46dd-8481-3e8f1e4a8d5e.png)
The graph in the example is shown below.
![image](https://user-images.githubusercontent.com/37436429/161026494-5f44928a-6ed1-4ebe-8eee-f4310ae4d6d3.png)

The process of my calculations is 
a. Copy the INCAR CONTCAR POTCAR KPOINTS WAVECAR calculated in the "C0" folder to the "WSWQ" folder created in all the folders under the "groud" folder;
b. Copy the calculated WAVECAR from all the "groud" folders into their respective "WSWQ" folders and rename them as WAVECAR.qqq;
c. Add ALGO=None and LWSWQ=.TRUE to INCAR and do a VASP calculation to get the WSWQ file.

The structure and calculation parameters used for the calculations were taken from https://nomad-lab.eu/. The version of VASP used is 5.4.4. I'm not quite sure if my calculation steps or parameters are correct.

I am wondering if someone could kindly share me the input files and the necessary information about it. I promise they will be used only for research purposed. If it's too much trouble, could anyone send me some relevant information?

Thank you very much for your kind consideration and I am looking forward to your early reply.

Best regards!

Changqing lin

[nonrad.zip](https://github.com/mturiansky/nonrad/files/8388205/nonrad.zip)

**Comment by iamcqlin** [comment]
Hi Mark，

I completed the calculations using vasp 6.3.0 and the results are in good agreement with the literature. But i haven't tested the recompiled vasp5.4.4 yet.

Thank you very much for your kind consideration.
Best regards!

Changqing lin

**Comment by mturiansky** [comment]
No problem. Glad to hear you're using nonrad. Let me know if you have any further questions.

Best,
Mark

**Comment by msehabibur** [comment]
@iamcqlin can you please explain why you chose these KPOINTS: 

Manually defined mesh
   1
Reciprocal lattice
   0.25  0.25   0.25     1

**Comment by iamcqlin** [comment]
> @iamcqlin can you please explain why you chose these KPOINTS:
> 
> Manually defined mesh 1 Reciprocal lattice 0.25 0.25 0.25 1

Hi~

The details of my calculations are from the article [Computer Physics Communications 267 (2021) 108056].
0.25 0.25 0.25 refers to the mean-value point in the Brillouin zone of cubic crystals, as you can learn from the article [Phys. Rev. B 7 (1973) 5212-5215]. This value seems to be limited to cubic cells.


Best
Changqing lin

**Comment by msehabibur** [comment]
Hi, I used your DFT input files to reproduce the defect level, but I got something different. Can you please check your files? @iamcqlin

**Comment by maybenewborn** [comment]
Can you please explain why you set ‘NELECT=383’ which was find in ’nonrad-master/test_files/vasprun.xml.0‘
In my opinion, it should be ’NELECT=863‘. Thanks.

**Comment by iamcqlin** [comment]
> Can you please explain why you set ‘NELECT=383’ which was find in ’nonrad-master/test_files/vasprun.xml.0‘ In my opinion, it should be ’NELECT=863‘. Thanks.

Hi,

I think it's a result of the difference in the pseudopotentials. In the example, the number of valence electrons in the Ga, N and C pseudopotentials are 3, 5 and 4 respectively, and it is easy to calculate that the total number of electrons is 48 × 3+47 × 5+4=383.
I gauss the Ga pseudopotential you probably used takes into account the electrons in its 3d orbitals, and the number of valence electrons is 13, so you get 48 × 13+47 × 5+4=863.
I think that in the GaN system, whether or not you include the d orbitals has little effect on the results of the calculations, but reducing the number of electrons does reduce the cost of the calculations. Of course, I'm not sure if substituting different pseudopotentials would make much difference to the calculation results, which you can test yourself.

Best
Changqing lin

**Comment by Samarmf** [comment]
Can you please advise where I can find The structure and calculation parameters used for the calculations?

**Comment by iamcqlin** [comment]
> 您能告诉我在哪里可以找到用于计算的结构和计算参数吗？
Hi. 
I'm not the author, so you can refer to the inputs and outputs of my test if you like.
[nonrad.zip](https://github.com/user-attachments/files/18427421/nonrad.zip)

**Comment by mturiansky** [comment]
The original calculations are [here](https://nomad-lab.eu/prod/v1/gui/dataset/id/9ZU8suSLSsGImuAV0jr0mQ).

**Comment by Samarmf** [comment]
Thanks all.




Best Regards,
Samar Fawzy, PhD
The American University in Cairo
