### ISSUE TITLE
Electron Capture Coefficient

### ISSUE THREAD

**Issue by Arindamsannyal** [mturiansky/nonrad#3]
Dear Altruists

Thank you very much for developing such a nice tool to calculate the SRH recombination coefficient. I found that the notebook of the 'nonrad' code shows how to calculate the hole capture coefficient for 'C' substitution at 'N' sites of 'GaN'. To calculate the SRH recombination coefficient (A), we would also need the electron capture coefficient as well. 

In the case of the electron capture coefficient, the 'nonrad' paper suggests using 'dE=Eg-ε(0/-)'. I would like to know, to calculate the electron capture coefficient, is it sufficient to use only the 'dE=Eg-ε(0/-)' in the code of capture coefficient, or do I also need to calculate the electron-phonon coupling matrix element (WSWQ files) as well. If I need to calculate the WSWQ files, then should I calculate them in the excited states?

Thank you very much for your time and kind consideration. 

Sincerely
Arindam Sannyal

**Comment by mturiansky** [comment]
Thanks for your interest in the nonrad code.

> To calculate the SRH recombination coefficient (A), we would also need the electron capture coefficient as well.

The SRH recombination coefficient is the product of the defect density and the total capture coefficient. So yes, you would also need to figure out electron capture to complete the cycle. However, you do not need to run the code to know that nonradiative electron capture will be negligible. The distance of the transition level from the CBM will be ~2.5 eV in GaN, for which the nonradiative rate will be negligibly small. Radiative capture, or other capture processes, will likely dominate. You also need to consider all possible charge state transition levels for the defect.

> I would like to know, to calculate the electron capture coefficient, is it sufficient to use only the 'dE=Eg-ε(0/-)' in the code of capture coefficient and use the same electron-phonon coupling matrix element (WSWQ files) around point 1 of the potential energy surface (PES). Or, I should calculate the WSWQ files around point 3 of PES as well. If so, then which bands should I consider to calculate the Wif, the VBM, or CBM?

You would start by constructing a "new" configuration coordinate diagram for the electron capture process. In this case, the initial excited state corresponds to the neutral defect with an electron in the CBM, and the final state is the negative defect. Thus not only has the energy changed, but the phonon frequencies are exchanged. You want to calculate the electron-phonon coupling in the neutral charge state, which corresponds to point 3 in this "new" CCD. However, point 3 in the "new" CCD is the same as point 1 in the "old" CCD. As a result, you can re-use your WSWQ files. Finally, you should consider the matrix element between the CBM and the defect states, but as I said, they can be extracted from the old WSWQ files.

**Comment by Arindamsannyal** [comment]
Dear Mark

Thank you very much for your kind response and suggestions.

Sincerely
Arindam Sannyal
