### ISSUE TITLE
About the calculation of the excited state

### ISSUE THREAD

**Issue by wangd11** [mturiansky/nonrad#7]
To calculate the configuration coordinate diagram (CCD) for a donor defect, assuming the ground state is D⁰ and the excited state involves an electron transition to the conduction band (D⁺+ e⁻), should the excited state structure be determined by optimizing the structure of the positively charged defect system (D⁺), or by using constrained DFT to optimize a neutral system structure with specific occupancy settings for the donor level and the conduction band bottom? Thanks in advance!

**Comment by mturiansky** [comment]
Most likely, you use the positively charged defect system. The assumption is that you have dilute defect/carrier concentrations for which the case of D^+ + e^- most resembles the calculation of D^+ (i.e., the presence of e^- in the conduction band in a dilute concentration does not change the physics). In theory, this is not universally true; e.g., in some systems there can be strong exciton binding, such that a calculation of D^+ alone would not capture the physics of e^- binding to the defect. This usually isn't relevant for most cases of trying to calculate nonradiative capture. (Also, it's questionable if you can even represent this physics in a small supercell with an explicit electron added...)
